### ISSUE TITLE
rexp is not defined

### ISSUE THREAD

**Issue by MatheusTran** [MichielVerloop/Latex-to-SMT-Converter#1]
Hello, I am trying to use this, however it does not seem to work.

I am using the latest versions of the libraries, however it gives me this error
``
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\parsimonious\grammar.py", line 287, in resolve_refs
    cur = rule_map[str(cur)]
          ~~~~~~~~^^^^^^^^^^
KeyError: 'rexp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Matheus\Desktop\github\z3\Latex-to-SMT-Converter\cli.py", line 3, in <module>
    from latex_to_smt import convert, get_globals
  File "C:\Users\Matheus\Desktop\github\z3\Latex-to-SMT-Converter\latex_to_smt.py", line 7, in <module>
    from grammar import BoolGrammar
  File "C:\Users\Matheus\Desktop\github\z3\Latex-to-SMT-Converter\grammar.py", line 6, in <module>
    class BoolGrammar:
  File "C:\Users\Matheus\Desktop\github\z3\Latex-to-SMT-Converter\grammar.py", line 7, in BoolGrammar
    latex_grammar = Grammar(
                    ^^^^^^^^
  File "C:\Python311\Lib\site-packages\parsimonious\grammar.py", line 66, in __init__
    exprs, first = self._expressions_from_rules(rules, decorated_custom_rules)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\parsimonious\grammar.py", line 103, in _expressions_from_rules
    return RuleVisitor(custom_rules).visit(tree)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\parsimonious\nodes.py", line 213, in visit
    return method(node, [self.visit(n) for n in node])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\parsimonious\grammar.py", line 474, in visit_rules
    rule_map[name] = rule.resolve_refs(rule_map)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\parsimonious\expressions.py", line 329, in resolve_refs
    self.members = tuple(m.resolve_refs(rule_map) for m in self.members)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\parsimonious\expressions.py", line 329, in <genexpr>
    self.members = tuple(m.resolve_refs(rule_map) for m in self.members)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\parsimonious\grammar.py", line 289, in resolve_refs
    raise UndefinedLabel(cur)
parsimonious.exceptions.UndefinedLabel: The label "rexp" was never defined.
``

I tried downgrading the dependencies, however it gives a different error.

**Comment by MichielVerloop** [comment]
Hi @scaevitas, this seems to be an issue caused by a newer version of parsimonious.
I added an easy way to install the required versions of the dependencies in the latest commits.
If you pull the new version, you should be able to set up the dependencies with the right versions by running `pip install -r requirements.txt`.

If you still experience 'the different error' after pulling the new version and installing the correct dependencies, there's a good chance that the error is caused by your input. Try running one of the example commands listed in the README.

**Comment by scaevitas** [comment]
I actually figured out an easier method, in grammar, I just wrote "rexp = rexpr" and everything seems to be working fine

**Comment by MichielVerloop** [comment]
@scaevitas I went ahead and looked at the changes in parsimonious, found the issue and resolved it in the newest version. While I think your hack should work, updating to the newest version is likely less error-prone.
